#index:
#    path: /
#    controller: App\Controller\DefaultController::index
reserve_hotel:
    path: /hotel/{id}/reserve
    controller: 'App\Controller\HotelController::reserve'
    methods: ['GET', 'POST']
    requirements:
        id: '\d+'





reservation_modifier:
    path: /reservation/modifier/{id}
    controller: App\Controller\YourController::modifierAction
    methods: [GET, POST]